# Generated by Django 3.2.12 on 2022-03-02 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20220302_0153'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postimages',
            table='post_images',
        ),
    ]
