# Generated by Django 3.2.12 on 2022-03-02 18:11

from django.db import migrations, models
import post.utils


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postimages_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=post.utils.post_image_s3_upload),
        ),
    ]
